// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/flokiorg/lokihub/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// ChangeUnlockPassword provides a mock function for the type MockConfig
func (_mock *MockConfig) ChangeUnlockPassword(currentUnlockPassword string, newUnlockPassword string) error {
	ret := _mock.Called(currentUnlockPassword, newUnlockPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangeUnlockPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(currentUnlockPassword, newUnlockPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_ChangeUnlockPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeUnlockPassword'
type MockConfig_ChangeUnlockPassword_Call struct {
	*mock.Call
}

// ChangeUnlockPassword is a helper method to define mock.On call
//   - currentUnlockPassword
//   - newUnlockPassword
func (_e *MockConfig_Expecter) ChangeUnlockPassword(currentUnlockPassword interface{}, newUnlockPassword interface{}) *MockConfig_ChangeUnlockPassword_Call {
	return &MockConfig_ChangeUnlockPassword_Call{Call: _e.mock.On("ChangeUnlockPassword", currentUnlockPassword, newUnlockPassword)}
}

func (_c *MockConfig_ChangeUnlockPassword_Call) Run(run func(currentUnlockPassword string, newUnlockPassword string)) *MockConfig_ChangeUnlockPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockConfig_ChangeUnlockPassword_Call) Return(err error) *MockConfig_ChangeUnlockPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfig_ChangeUnlockPassword_Call) RunAndReturn(run func(currentUnlockPassword string, newUnlockPassword string) error) *MockConfig_ChangeUnlockPassword_Call {
	_c.Call.Return(run)
	return _c
}

// CheckUnlockPassword provides a mock function for the type MockConfig
func (_mock *MockConfig) CheckUnlockPassword(password string) bool {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for CheckUnlockPassword")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_CheckUnlockPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUnlockPassword'
type MockConfig_CheckUnlockPassword_Call struct {
	*mock.Call
}

// CheckUnlockPassword is a helper method to define mock.On call
//   - password
func (_e *MockConfig_Expecter) CheckUnlockPassword(password interface{}) *MockConfig_CheckUnlockPassword_Call {
	return &MockConfig_CheckUnlockPassword_Call{Call: _e.mock.On("CheckUnlockPassword", password)}
}

func (_c *MockConfig_CheckUnlockPassword_Call) Run(run func(password string)) *MockConfig_CheckUnlockPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_CheckUnlockPassword_Call) Return(b bool) *MockConfig_CheckUnlockPassword_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_CheckUnlockPassword_Call) RunAndReturn(run func(password string) bool) *MockConfig_CheckUnlockPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockConfig
func (_mock *MockConfig) Get(key string, encryptionKey string) (string, error) {
	ret := _mock.Called(key, encryptionKey)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(key, encryptionKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(key, encryptionKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(key, encryptionKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfig_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConfig_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key
//   - encryptionKey
func (_e *MockConfig_Expecter) Get(key interface{}, encryptionKey interface{}) *MockConfig_Get_Call {
	return &MockConfig_Get_Call{Call: _e.mock.On("Get", key, encryptionKey)}
}

func (_c *MockConfig_Get_Call) Run(run func(key string, encryptionKey string)) *MockConfig_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockConfig_Get_Call) Return(s string, err error) *MockConfig_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConfig_Get_Call) RunAndReturn(run func(key string, encryptionKey string) (string, error)) *MockConfig_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlokicoinDisplayFormat provides a mock function for the type MockConfig
func (_mock *MockConfig) GetFlokicoinDisplayFormat() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFlokicoinDisplayFormat")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_GetFlokicoinDisplayFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlokicoinDisplayFormat'
type MockConfig_GetFlokicoinDisplayFormat_Call struct {
	*mock.Call
}

// GetFlokicoinDisplayFormat is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetFlokicoinDisplayFormat() *MockConfig_GetFlokicoinDisplayFormat_Call {
	return &MockConfig_GetFlokicoinDisplayFormat_Call{Call: _e.mock.On("GetFlokicoinDisplayFormat")}
}

func (_c *MockConfig_GetFlokicoinDisplayFormat_Call) Run(run func()) *MockConfig_GetFlokicoinDisplayFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetFlokicoinDisplayFormat_Call) Return(s string) *MockConfig_GetFlokicoinDisplayFormat_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_GetFlokicoinDisplayFormat_Call) RunAndReturn(run func() string) *MockConfig_GetFlokicoinDisplayFormat_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrency provides a mock function for the type MockConfig
func (_mock *MockConfig) GetCurrency() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrency")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_GetCurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrency'
type MockConfig_GetCurrency_Call struct {
	*mock.Call
}

// GetCurrency is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetCurrency() *MockConfig_GetCurrency_Call {
	return &MockConfig_GetCurrency_Call{Call: _e.mock.On("GetCurrency")}
}

func (_c *MockConfig_GetCurrency_Call) Run(run func()) *MockConfig_GetCurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetCurrency_Call) Return(s string) *MockConfig_GetCurrency_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_GetCurrency_Call) RunAndReturn(run func() string) *MockConfig_GetCurrency_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnv provides a mock function for the type MockConfig
func (_mock *MockConfig) GetEnv() *config.AppConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEnv")
	}

	var r0 *config.AppConfig
	if returnFunc, ok := ret.Get(0).(func() *config.AppConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.AppConfig)
		}
	}
	return r0
}

// MockConfig_GetEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnv'
type MockConfig_GetEnv_Call struct {
	*mock.Call
}

// GetEnv is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetEnv() *MockConfig_GetEnv_Call {
	return &MockConfig_GetEnv_Call{Call: _e.mock.On("GetEnv")}
}

func (_c *MockConfig_GetEnv_Call) Run(run func()) *MockConfig_GetEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetEnv_Call) Return(appConfig *config.AppConfig) *MockConfig_GetEnv_Call {
	_c.Call.Return(appConfig)
	return _c
}

func (_c *MockConfig_GetEnv_Call) RunAndReturn(run func() *config.AppConfig) *MockConfig_GetEnv_Call {
	_c.Call.Return(run)
	return _c
}

// GetJWTSecret provides a mock function for the type MockConfig
func (_mock *MockConfig) GetJWTSecret() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJWTSecret")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfig_GetJWTSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJWTSecret'
type MockConfig_GetJWTSecret_Call struct {
	*mock.Call
}

// GetJWTSecret is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetJWTSecret() *MockConfig_GetJWTSecret_Call {
	return &MockConfig_GetJWTSecret_Call{Call: _e.mock.On("GetJWTSecret")}
}

func (_c *MockConfig_GetJWTSecret_Call) Run(run func()) *MockConfig_GetJWTSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetJWTSecret_Call) Return(s string, err error) *MockConfig_GetJWTSecret_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConfig_GetJWTSecret_Call) RunAndReturn(run func() (string, error)) *MockConfig_GetJWTSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetMempoolUrl provides a mock function for the type MockConfig
func (_mock *MockConfig) GetMempoolUrl() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMempoolUrl")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_GetMempoolUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMempoolUrl'
type MockConfig_GetMempoolUrl_Call struct {
	*mock.Call
}

// GetMempoolUrl is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetMempoolUrl() *MockConfig_GetMempoolUrl_Call {
	return &MockConfig_GetMempoolUrl_Call{Call: _e.mock.On("GetMempoolUrl")}
}

func (_c *MockConfig_GetMempoolUrl_Call) Run(run func()) *MockConfig_GetMempoolUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetMempoolUrl_Call) Return(s string) *MockConfig_GetMempoolUrl_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_GetMempoolUrl_Call) RunAndReturn(run func() string) *MockConfig_GetMempoolUrl_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetwork provides a mock function for the type MockConfig
func (_mock *MockConfig) GetNetwork() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNetwork")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_GetNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetwork'
type MockConfig_GetNetwork_Call struct {
	*mock.Call
}

// GetNetwork is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetNetwork() *MockConfig_GetNetwork_Call {
	return &MockConfig_GetNetwork_Call{Call: _e.mock.On("GetNetwork")}
}

func (_c *MockConfig_GetNetwork_Call) Run(run func()) *MockConfig_GetNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetNetwork_Call) Return(s string) *MockConfig_GetNetwork_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_GetNetwork_Call) RunAndReturn(run func() string) *MockConfig_GetNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelayUrls provides a mock function for the type MockConfig
func (_mock *MockConfig) GetRelayUrls() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRelayUrls")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockConfig_GetRelayUrls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelayUrls'
type MockConfig_GetRelayUrls_Call struct {
	*mock.Call
}

// GetRelayUrls is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetRelayUrls() *MockConfig_GetRelayUrls_Call {
	return &MockConfig_GetRelayUrls_Call{Call: _e.mock.On("GetRelayUrls")}
}

func (_c *MockConfig_GetRelayUrls_Call) Run(run func()) *MockConfig_GetRelayUrls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetRelayUrls_Call) Return(strings []string) *MockConfig_GetRelayUrls_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockConfig_GetRelayUrls_Call) RunAndReturn(run func() []string) *MockConfig_GetRelayUrls_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUnlockPasswordCheck provides a mock function for the type MockConfig
func (_mock *MockConfig) SaveUnlockPasswordCheck(encryptionKey string) error {
	ret := _mock.Called(encryptionKey)

	if len(ret) == 0 {
		panic("no return value specified for SaveUnlockPasswordCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(encryptionKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_SaveUnlockPasswordCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUnlockPasswordCheck'
type MockConfig_SaveUnlockPasswordCheck_Call struct {
	*mock.Call
}

// SaveUnlockPasswordCheck is a helper method to define mock.On call
//   - encryptionKey
func (_e *MockConfig_Expecter) SaveUnlockPasswordCheck(encryptionKey interface{}) *MockConfig_SaveUnlockPasswordCheck_Call {
	return &MockConfig_SaveUnlockPasswordCheck_Call{Call: _e.mock.On("SaveUnlockPasswordCheck", encryptionKey)}
}

func (_c *MockConfig_SaveUnlockPasswordCheck_Call) Run(run func(encryptionKey string)) *MockConfig_SaveUnlockPasswordCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_SaveUnlockPasswordCheck_Call) Return(err error) *MockConfig_SaveUnlockPasswordCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfig_SaveUnlockPasswordCheck_Call) RunAndReturn(run func(encryptionKey string) error) *MockConfig_SaveUnlockPasswordCheck_Call {
	_c.Call.Return(run)
	return _c
}

// SetAutoUnlockPassword provides a mock function for the type MockConfig
func (_mock *MockConfig) SetAutoUnlockPassword(unlockPassword string) error {
	ret := _mock.Called(unlockPassword)

	if len(ret) == 0 {
		panic("no return value specified for SetAutoUnlockPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(unlockPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_SetAutoUnlockPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAutoUnlockPassword'
type MockConfig_SetAutoUnlockPassword_Call struct {
	*mock.Call
}

// SetAutoUnlockPassword is a helper method to define mock.On call
//   - unlockPassword
func (_e *MockConfig_Expecter) SetAutoUnlockPassword(unlockPassword interface{}) *MockConfig_SetAutoUnlockPassword_Call {
	return &MockConfig_SetAutoUnlockPassword_Call{Call: _e.mock.On("SetAutoUnlockPassword", unlockPassword)}
}

func (_c *MockConfig_SetAutoUnlockPassword_Call) Run(run func(unlockPassword string)) *MockConfig_SetAutoUnlockPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_SetAutoUnlockPassword_Call) Return(err error) *MockConfig_SetAutoUnlockPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfig_SetAutoUnlockPassword_Call) RunAndReturn(run func(unlockPassword string) error) *MockConfig_SetAutoUnlockPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SetFlokicoinDisplayFormat provides a mock function for the type MockConfig
func (_mock *MockConfig) SetFlokicoinDisplayFormat(value string) error {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for SetFlokicoinDisplayFormat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_SetFlokicoinDisplayFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFlokicoinDisplayFormat'
type MockConfig_SetFlokicoinDisplayFormat_Call struct {
	*mock.Call
}

// SetFlokicoinDisplayFormat is a helper method to define mock.On call
//   - value
func (_e *MockConfig_Expecter) SetFlokicoinDisplayFormat(value interface{}) *MockConfig_SetFlokicoinDisplayFormat_Call {
	return &MockConfig_SetFlokicoinDisplayFormat_Call{Call: _e.mock.On("SetFlokicoinDisplayFormat", value)}
}

func (_c *MockConfig_SetFlokicoinDisplayFormat_Call) Run(run func(value string)) *MockConfig_SetFlokicoinDisplayFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_SetFlokicoinDisplayFormat_Call) Return(err error) *MockConfig_SetFlokicoinDisplayFormat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfig_SetFlokicoinDisplayFormat_Call) RunAndReturn(run func(value string) error) *MockConfig_SetFlokicoinDisplayFormat_Call {
	_c.Call.Return(run)
	return _c
}

// SetCurrency provides a mock function for the type MockConfig
func (_mock *MockConfig) SetCurrency(value string) error {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for SetCurrency")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_SetCurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCurrency'
type MockConfig_SetCurrency_Call struct {
	*mock.Call
}

// SetCurrency is a helper method to define mock.On call
//   - value
func (_e *MockConfig_Expecter) SetCurrency(value interface{}) *MockConfig_SetCurrency_Call {
	return &MockConfig_SetCurrency_Call{Call: _e.mock.On("SetCurrency", value)}
}

func (_c *MockConfig_SetCurrency_Call) Run(run func(value string)) *MockConfig_SetCurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_SetCurrency_Call) Return(err error) *MockConfig_SetCurrency_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfig_SetCurrency_Call) RunAndReturn(run func(value string) error) *MockConfig_SetCurrency_Call {
	_c.Call.Return(run)
	return _c
}

// SetIgnore provides a mock function for the type MockConfig
func (_mock *MockConfig) SetIgnore(key string, value string, encryptionKey string) error {
	ret := _mock.Called(key, value, encryptionKey)

	if len(ret) == 0 {
		panic("no return value specified for SetIgnore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(key, value, encryptionKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_SetIgnore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIgnore'
type MockConfig_SetIgnore_Call struct {
	*mock.Call
}

// SetIgnore is a helper method to define mock.On call
//   - key
//   - value
//   - encryptionKey
func (_e *MockConfig_Expecter) SetIgnore(key interface{}, value interface{}, encryptionKey interface{}) *MockConfig_SetIgnore_Call {
	return &MockConfig_SetIgnore_Call{Call: _e.mock.On("SetIgnore", key, value, encryptionKey)}
}

func (_c *MockConfig_SetIgnore_Call) Run(run func(key string, value string, encryptionKey string)) *MockConfig_SetIgnore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockConfig_SetIgnore_Call) Return(err error) *MockConfig_SetIgnore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfig_SetIgnore_Call) RunAndReturn(run func(key string, value string, encryptionKey string) error) *MockConfig_SetIgnore_Call {
	_c.Call.Return(run)
	return _c
}

// SetUpdate provides a mock function for the type MockConfig
func (_mock *MockConfig) SetUpdate(key string, value string, encryptionKey string) error {
	ret := _mock.Called(key, value, encryptionKey)

	if len(ret) == 0 {
		panic("no return value specified for SetUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(key, value, encryptionKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_SetUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUpdate'
type MockConfig_SetUpdate_Call struct {
	*mock.Call
}

// SetUpdate is a helper method to define mock.On call
//   - key
//   - value
//   - encryptionKey
func (_e *MockConfig_Expecter) SetUpdate(key interface{}, value interface{}, encryptionKey interface{}) *MockConfig_SetUpdate_Call {
	return &MockConfig_SetUpdate_Call{Call: _e.mock.On("SetUpdate", key, value, encryptionKey)}
}

func (_c *MockConfig_SetUpdate_Call) Run(run func(key string, value string, encryptionKey string)) *MockConfig_SetUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockConfig_SetUpdate_Call) Return(err error) *MockConfig_SetUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfig_SetUpdate_Call) RunAndReturn(run func(key string, value string, encryptionKey string) error) *MockConfig_SetUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultWorkDir provides a mock function for the type MockConfig
func (_mock *MockConfig) GetDefaultWorkDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultWorkDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_GetDefaultWorkDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultWorkDir'
type MockConfig_GetDefaultWorkDir_Call struct {
	*mock.Call
}

// GetDefaultWorkDir is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetDefaultWorkDir() *MockConfig_GetDefaultWorkDir_Call {
	return &MockConfig_GetDefaultWorkDir_Call{Call: _e.mock.On("GetDefaultWorkDir")}
}

func (_c *MockConfig_GetDefaultWorkDir_Call) Run(run func()) *MockConfig_GetDefaultWorkDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetDefaultWorkDir_Call) Return(r0 string) *MockConfig_GetDefaultWorkDir_Call {
	_c.Call.Return(r0)
	return _c
}

func (_c *MockConfig_GetDefaultWorkDir_Call) RunAndReturn(run func() string) *MockConfig_GetDefaultWorkDir_Call {
	_c.Call.Return(run)
	return _c
}

// SetMessageboardNwcUrl provides a mock function for the type MockConfig
func (_mock *MockConfig) SetMessageboardNwcUrl(value string) error {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for SetMessageboardNwcUrl")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GetRelay provides a mock function for the type MockConfig
func (_mock *MockConfig) GetRelay() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRelay")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SetRelay provides a mock function for the type MockConfig
func (_mock *MockConfig) SetRelay(value string) error {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for SetRelay")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SetupCompleted provides a mock function for the type MockConfig
func (_mock *MockConfig) SetupCompleted() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SetupCompleted")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_SetupCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupCompleted'
type MockConfig_SetupCompleted_Call struct {
	*mock.Call
}

// SetupCompleted is a helper method to define mock.On call
func (_e *MockConfig_Expecter) SetupCompleted() *MockConfig_SetupCompleted_Call {
	return &MockConfig_SetupCompleted_Call{Call: _e.mock.On("SetupCompleted")}
}

func (_c *MockConfig_SetupCompleted_Call) Run(run func()) *MockConfig_SetupCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_SetupCompleted_Call) Return(b bool) *MockConfig_SetupCompleted_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_SetupCompleted_Call) RunAndReturn(run func() bool) *MockConfig_SetupCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// GetLokihubServicesURL provides a mock function for the type MockConfig
func (_mock *MockConfig) GetLokihubServicesURL() string {
	ret := _mock.Called()
	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SetLokihubServicesURL provides a mock function for the type MockConfig
func (_mock *MockConfig) SetLokihubServicesURL(value string) error {
	ret := _mock.Called(value)
	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GetSwapServiceURL provides a mock function for the type MockConfig
func (_mock *MockConfig) GetSwapServiceURL() string {
	ret := _mock.Called()
	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// GetMessageboardNwcUrl provides a mock function for the type MockConfig
func (_mock *MockConfig) GetMessageboardNwcUrl() string {
	ret := _mock.Called()
	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SetSwapServiceURL provides a mock function for the type MockConfig
func (_mock *MockConfig) SetSwapServiceURL(value string) error {
	ret := _mock.Called(value)
	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Unlock provides a mock function for the type MockConfig
func (_mock *MockConfig) Unlock(encryptionKey string) error {
	ret := _mock.Called(encryptionKey)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(encryptionKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockConfig_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - encryptionKey
func (_e *MockConfig_Expecter) Unlock(encryptionKey interface{}) *MockConfig_Unlock_Call {
	return &MockConfig_Unlock_Call{Call: _e.mock.On("Unlock", encryptionKey)}
}

func (_c *MockConfig_Unlock_Call) Run(run func(encryptionKey string)) *MockConfig_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_Unlock_Call) Return(err error) *MockConfig_Unlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfig_Unlock_Call) RunAndReturn(run func(encryptionKey string) error) *MockConfig_Unlock_Call {
	_c.Call.Return(run)
	return _c
}

// EnableRebalance provides a mock function for the type MockConfig
func (_mock *MockConfig) EnableRebalance() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnableRebalance")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_EnableRebalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableRebalance'
type MockConfig_EnableRebalance_Call struct {
	*mock.Call
}

// EnableRebalance is a helper method to define mock.On call
func (_e *MockConfig_Expecter) EnableRebalance() *MockConfig_EnableRebalance_Call {
	return &MockConfig_EnableRebalance_Call{Call: _e.mock.On("EnableRebalance")}
}

func (_c *MockConfig_EnableRebalance_Call) Run(run func()) *MockConfig_EnableRebalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_EnableRebalance_Call) Return(b bool) *MockConfig_EnableRebalance_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_EnableRebalance_Call) RunAndReturn(run func() bool) *MockConfig_EnableRebalance_Call {
	_c.Call.Return(run)
	return _c
}

// EnableSwap provides a mock function for the type MockConfig
func (_mock *MockConfig) EnableSwap() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnableSwap")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_EnableSwap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableSwap'
type MockConfig_EnableSwap_Call struct {
	*mock.Call
}

// EnableSwap is a helper method to define mock.On call
func (_e *MockConfig_Expecter) EnableSwap() *MockConfig_EnableSwap_Call {
	return &MockConfig_EnableSwap_Call{Call: _e.mock.On("EnableSwap")}
}

func (_c *MockConfig_EnableSwap_Call) Run(run func()) *MockConfig_EnableSwap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_EnableSwap_Call) Return(b bool) *MockConfig_EnableSwap_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_EnableSwap_Call) RunAndReturn(run func() bool) *MockConfig_EnableSwap_Call {
	_c.Call.Return(run)
	return _c
}

// GetRebalanceServiceUrl provides a mock function for the type MockConfig
func (_mock *MockConfig) GetRebalanceServiceUrl() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRebalanceServiceUrl")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_GetRebalanceServiceUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRebalanceServiceUrl'
type MockConfig_GetRebalanceServiceUrl_Call struct {
	*mock.Call
}

// GetRebalanceServiceUrl is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetRebalanceServiceUrl() *MockConfig_GetRebalanceServiceUrl_Call {
	return &MockConfig_GetRebalanceServiceUrl_Call{Call: _e.mock.On("GetRebalanceServiceUrl")}
}

func (_c *MockConfig_GetRebalanceServiceUrl_Call) Run(run func()) *MockConfig_GetRebalanceServiceUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetRebalanceServiceUrl_Call) Return(s string) *MockConfig_GetRebalanceServiceUrl_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_GetRebalanceServiceUrl_Call) RunAndReturn(run func() string) *MockConfig_GetRebalanceServiceUrl_Call {
	_c.Call.Return(run)
	return _c
}

// GetMempoolApi provides a mock function for the type MockConfig
func (_mock *MockConfig) GetMempoolApi() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMempoolApi")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_GetMempoolApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMempoolApi'
type MockConfig_GetMempoolApi_Call struct {
	*mock.Call
}

// GetMempoolApi is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetMempoolApi() *MockConfig_GetMempoolApi_Call {
	return &MockConfig_GetMempoolApi_Call{Call: _e.mock.On("GetMempoolApi")}
}

func (_c *MockConfig_GetMempoolApi_Call) Run(run func()) *MockConfig_GetMempoolApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetMempoolApi_Call) Return(s string) *MockConfig_GetMempoolApi_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_GetMempoolApi_Call) RunAndReturn(run func() string) *MockConfig_GetMempoolApi_Call {
	_c.Call.Return(run)
	return _c
}

// SetMempoolApi provides a mock function for the type MockConfig
func (_mock *MockConfig) SetMempoolApi(value string) error {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for SetMempoolApi")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_SetMempoolApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMempoolApi'
type MockConfig_SetMempoolApi_Call struct {
	*mock.Call
}

// SetMempoolApi is a helper method to define mock.On call
//   - value
func (_e *MockConfig_Expecter) SetMempoolApi(value interface{}) *MockConfig_SetMempoolApi_Call {
	return &MockConfig_SetMempoolApi_Call{Call: _e.mock.On("SetMempoolApi", value)}
}

func (_c *MockConfig_SetMempoolApi_Call) Run(run func(value string)) *MockConfig_SetMempoolApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_SetMempoolApi_Call) Return(err error) *MockConfig_SetMempoolApi_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfig_SetMempoolApi_Call) RunAndReturn(run func(value string) error) *MockConfig_SetMempoolApi_Call {
	_c.Call.Return(run)
	return _c
}

// SetEnableSwap provides a mock function for the type MockConfig
func (_mock *MockConfig) SetEnableSwap(value bool) error {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for SetEnableSwap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(bool) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_SetEnableSwap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnableSwap'
type MockConfig_SetEnableSwap_Call struct {
	*mock.Call
}

// SetEnableSwap is a helper method to define mock.On call
//   - value
func (_e *MockConfig_Expecter) SetEnableSwap(value interface{}) *MockConfig_SetEnableSwap_Call {
	return &MockConfig_SetEnableSwap_Call{Call: _e.mock.On("SetEnableSwap", value)}
}

func (_c *MockConfig_SetEnableSwap_Call) Run(run func(value bool)) *MockConfig_SetEnableSwap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockConfig_SetEnableSwap_Call) Return(err error) *MockConfig_SetEnableSwap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfig_SetEnableSwap_Call) RunAndReturn(run func(value bool) error) *MockConfig_SetEnableSwap_Call {
	_c.Call.Return(run)
	return _c
}

// EnableMessageboardNwc provides a mock function for the type MockConfig
func (_mock *MockConfig) EnableMessageboardNwc() bool {
	ret := _mock.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockConfig_EnableMessageboardNwc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableMessageboardNwc'
type MockConfig_EnableMessageboardNwc_Call struct {
	*mock.Call
}

// EnableMessageboardNwc is a helper method to define mock.On call
func (_e *MockConfig_Expecter) EnableMessageboardNwc() *MockConfig_EnableMessageboardNwc_Call {
	return &MockConfig_EnableMessageboardNwc_Call{Call: _e.mock.On("EnableMessageboardNwc")}
}

func (_c *MockConfig_EnableMessageboardNwc_Call) Run(run func()) *MockConfig_EnableMessageboardNwc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_EnableMessageboardNwc_Call) Return(_a0 bool) *MockConfig_EnableMessageboardNwc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfig_EnableMessageboardNwc_Call) RunAndReturn(run func() bool) *MockConfig_EnableMessageboardNwc_Call {
	_c.Call.Return(run)
	return _c
}

// SetEnableMessageboardNwc provides a mock function for the type MockConfig
func (_mock *MockConfig) SetEnableMessageboardNwc(enable bool) error {
	ret := _mock.Called(enable)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(enable)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfig_SetEnableMessageboardNwc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnableMessageboardNwc'
type MockConfig_SetEnableMessageboardNwc_Call struct {
	*mock.Call
}

// SetEnableMessageboardNwc is a helper method to define mock.On call
func (_e *MockConfig_Expecter) SetEnableMessageboardNwc(enable interface{}) *MockConfig_SetEnableMessageboardNwc_Call {
	return &MockConfig_SetEnableMessageboardNwc_Call{Call: _e.mock.On("SetEnableMessageboardNwc", enable)}
}

func (_c *MockConfig_SetEnableMessageboardNwc_Call) Run(run func(enable bool)) *MockConfig_SetEnableMessageboardNwc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockConfig_SetEnableMessageboardNwc_Call) Return(_a0 error) *MockConfig_SetEnableMessageboardNwc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfig_SetEnableMessageboardNwc_Call) RunAndReturn(run func(bool) error) *MockConfig_SetEnableMessageboardNwc_Call {
	_c.Call.Return(run)
	return _c
}

// GetLokihubStoreURL provides a mock function for the type MockConfig
func (_mock *MockConfig) GetLokihubStoreURL() string {
	ret := _mock.Called()
	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_GetLokihubStoreURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLokihubStoreURL'
type MockConfig_GetLokihubStoreURL_Call struct {
	*mock.Call
}

// GetLokihubStoreURL is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GetLokihubStoreURL() *MockConfig_GetLokihubStoreURL_Call {
	return &MockConfig_GetLokihubStoreURL_Call{Call: _e.mock.On("GetLokihubStoreURL")}
}

func (_c *MockConfig_GetLokihubStoreURL_Call) Run(run func()) *MockConfig_GetLokihubStoreURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GetLokihubStoreURL_Call) Return(_a0 string) *MockConfig_GetLokihubStoreURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfig_GetLokihubStoreURL_Call) RunAndReturn(run func() string) *MockConfig_GetLokihubStoreURL_Call {
	_c.Call.Return(run)
	return _c
}

// SetLokihubStoreURL provides a mock function for the type MockConfig
func (_mock *MockConfig) SetLokihubStoreURL(value string) error {
	ret := _mock.Called(value)
	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfig_SetLokihubStoreURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLokihubStoreURL'
type MockConfig_SetLokihubStoreURL_Call struct {
	*mock.Call
}

// SetLokihubStoreURL is a helper method to define mock.On call
func (_e *MockConfig_Expecter) SetLokihubStoreURL(value interface{}) *MockConfig_SetLokihubStoreURL_Call {
	return &MockConfig_SetLokihubStoreURL_Call{Call: _e.mock.On("SetLokihubStoreURL", value)}
}

func (_c *MockConfig_SetLokihubStoreURL_Call) Run(run func(value string)) *MockConfig_SetLokihubStoreURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfig_SetLokihubStoreURL_Call) Return(_a0 error) *MockConfig_SetLokihubStoreURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfig_SetLokihubStoreURL_Call) RunAndReturn(run func(string) error) *MockConfig_SetLokihubStoreURL_Call {
	_c.Call.Return(run)
	return _c
}
