// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	invoicesrpc "github.com/flokiorg/flnd/lnrpc/invoicesrpc"

	lnrpc "github.com/flokiorg/flnd/lnrpc"

	mock "github.com/stretchr/testify/mock"

	routerrpc "github.com/flokiorg/flnd/lnrpc/routerrpc"

	wrapper "github.com/flokiorg/lokihub/lnclient/lnd/wrapper"
)

// LightningClientWrapper is an autogenerated mock type for the LightningClientWrapper type
type LightningClientWrapper struct {
	mock.Mock
}

// AddHoldInvoice provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) AddHoldInvoice(ctx context.Context, req *invoicesrpc.AddHoldInvoiceRequest, options ...grpc.CallOption) (*invoicesrpc.AddHoldInvoiceResp, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddHoldInvoice")
	}

	var r0 *invoicesrpc.AddHoldInvoiceResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *invoicesrpc.AddHoldInvoiceRequest, ...grpc.CallOption) (*invoicesrpc.AddHoldInvoiceResp, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *invoicesrpc.AddHoldInvoiceRequest, ...grpc.CallOption) *invoicesrpc.AddHoldInvoiceResp); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*invoicesrpc.AddHoldInvoiceResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *invoicesrpc.AddHoldInvoiceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddInvoice provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) AddInvoice(ctx context.Context, req *lnrpc.Invoice, options ...grpc.CallOption) (*lnrpc.AddInvoiceResponse, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddInvoice")
	}

	var r0 *lnrpc.AddInvoiceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.Invoice, ...grpc.CallOption) (*lnrpc.AddInvoiceResponse, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.Invoice, ...grpc.CallOption) *lnrpc.AddInvoiceResponse); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lnrpc.AddInvoiceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *lnrpc.Invoice, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelInvoice provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) CancelInvoice(ctx context.Context, req *invoicesrpc.CancelInvoiceMsg, options ...grpc.CallOption) (*invoicesrpc.CancelInvoiceResp, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CancelInvoice")
	}

	var r0 *invoicesrpc.CancelInvoiceResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *invoicesrpc.CancelInvoiceMsg, ...grpc.CallOption) (*invoicesrpc.CancelInvoiceResp, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *invoicesrpc.CancelInvoiceMsg, ...grpc.CallOption) *invoicesrpc.CancelInvoiceResp); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*invoicesrpc.CancelInvoiceResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *invoicesrpc.CancelInvoiceMsg, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChannelBalance provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) ChannelBalance(ctx context.Context, req *lnrpc.ChannelBalanceRequest, options ...grpc.CallOption) (*lnrpc.ChannelBalanceResponse, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChannelBalance")
	}

	var r0 *lnrpc.ChannelBalanceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.ChannelBalanceRequest, ...grpc.CallOption) (*lnrpc.ChannelBalanceResponse, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.ChannelBalanceRequest, ...grpc.CallOption) *lnrpc.ChannelBalanceResponse); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lnrpc.ChannelBalanceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *lnrpc.ChannelBalanceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DecodeBolt11 provides a mock function with given fields: ctx, bolt11, options
func (_m *LightningClientWrapper) DecodeBolt11(ctx context.Context, bolt11 string, options ...grpc.CallOption) (*lnrpc.PayReq, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, bolt11)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DecodeBolt11")
	}

	var r0 *lnrpc.PayReq
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...grpc.CallOption) (*lnrpc.PayReq, error)); ok {
		return rf(ctx, bolt11, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...grpc.CallOption) *lnrpc.PayReq); ok {
		r0 = rf(ctx, bolt11, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lnrpc.PayReq)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, bolt11, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInfo provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) GetInfo(ctx context.Context, req *lnrpc.GetInfoRequest, options ...grpc.CallOption) (*lnrpc.GetInfoResponse, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 *lnrpc.GetInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.GetInfoRequest, ...grpc.CallOption) (*lnrpc.GetInfoResponse, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.GetInfoRequest, ...grpc.CallOption) *lnrpc.GetInfoResponse); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lnrpc.GetInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *lnrpc.GetInfoRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMainPubkey provides a mock function with no fields
func (_m *LightningClientWrapper) GetMainPubkey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMainPubkey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsIdentityPubkey provides a mock function with given fields: pubkey
func (_m *LightningClientWrapper) IsIdentityPubkey(pubkey string) bool {
	ret := _m.Called(pubkey)

	if len(ret) == 0 {
		panic("no return value specified for IsIdentityPubkey")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(pubkey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ListChannels provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) ListChannels(ctx context.Context, req *lnrpc.ListChannelsRequest, options ...grpc.CallOption) (*lnrpc.ListChannelsResponse, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListChannels")
	}

	var r0 *lnrpc.ListChannelsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.ListChannelsRequest, ...grpc.CallOption) (*lnrpc.ListChannelsResponse, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.ListChannelsRequest, ...grpc.CallOption) *lnrpc.ListChannelsResponse); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lnrpc.ListChannelsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *lnrpc.ListChannelsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LookupInvoice provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) LookupInvoice(ctx context.Context, req *lnrpc.PaymentHash, options ...grpc.CallOption) (*lnrpc.Invoice, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LookupInvoice")
	}

	var r0 *lnrpc.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.PaymentHash, ...grpc.CallOption) (*lnrpc.Invoice, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.PaymentHash, ...grpc.CallOption) *lnrpc.Invoice); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lnrpc.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *lnrpc.PaymentHash, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendPaymentSync provides a mock function with given fields: req, options
func (_m *LightningClientWrapper) SendPaymentSync(req *lnrpc.SendRequest, options ...grpc.CallOption) (*lnrpc.SendResponse, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SendPaymentSync")
	}

	var r0 *lnrpc.SendResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*lnrpc.SendRequest, ...grpc.CallOption) (*lnrpc.SendResponse, error)); ok {
		return rf(req, options...)
	}
	if rf, ok := ret.Get(0).(func(*lnrpc.SendRequest, ...grpc.CallOption) *lnrpc.SendResponse); ok {
		r0 = rf(req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lnrpc.SendResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*lnrpc.SendRequest, ...grpc.CallOption) error); ok {
		r1 = rf(req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettleInvoice provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) SettleInvoice(ctx context.Context, req *invoicesrpc.SettleInvoiceMsg, options ...grpc.CallOption) (*invoicesrpc.SettleInvoiceResp, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SettleInvoice")
	}

	var r0 *invoicesrpc.SettleInvoiceResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *invoicesrpc.SettleInvoiceMsg, ...grpc.CallOption) (*invoicesrpc.SettleInvoiceResp, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *invoicesrpc.SettleInvoiceMsg, ...grpc.CallOption) *invoicesrpc.SettleInvoiceResp); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*invoicesrpc.SettleInvoiceResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *invoicesrpc.SettleInvoiceMsg, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignMessage provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) SignMessage(ctx context.Context, req *lnrpc.SignMessageRequest, options ...grpc.CallOption) (*lnrpc.SignMessageResponse, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SignMessage")
	}

	var r0 *lnrpc.SignMessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.SignMessageRequest, ...grpc.CallOption) (*lnrpc.SignMessageResponse, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.SignMessageRequest, ...grpc.CallOption) *lnrpc.SignMessageResponse); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lnrpc.SignMessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *lnrpc.SignMessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeInvoices provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) SubscribeInvoices(ctx context.Context, req *lnrpc.InvoiceSubscription, options ...grpc.CallOption) (wrapper.SubscribeInvoicesWrapper, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeInvoices")
	}

	var r0 wrapper.SubscribeInvoicesWrapper
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.InvoiceSubscription, ...grpc.CallOption) (wrapper.SubscribeInvoicesWrapper, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.InvoiceSubscription, ...grpc.CallOption) wrapper.SubscribeInvoicesWrapper); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wrapper.SubscribeInvoicesWrapper)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *lnrpc.InvoiceSubscription, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribePayment provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) SubscribePayment(ctx context.Context, req *routerrpc.TrackPaymentRequest, options ...grpc.CallOption) (wrapper.SubscribePaymentWrapper, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribePayment")
	}

	var r0 wrapper.SubscribePaymentWrapper
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *routerrpc.TrackPaymentRequest, ...grpc.CallOption) (wrapper.SubscribePaymentWrapper, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *routerrpc.TrackPaymentRequest, ...grpc.CallOption) wrapper.SubscribePaymentWrapper); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wrapper.SubscribePaymentWrapper)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *routerrpc.TrackPaymentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeSingleInvoice provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) SubscribeSingleInvoice(ctx context.Context, req *invoicesrpc.SubscribeSingleInvoiceRequest, options ...grpc.CallOption) (wrapper.SubscribeSingleInvoiceWrapper, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeSingleInvoice")
	}

	var r0 wrapper.SubscribeSingleInvoiceWrapper
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *invoicesrpc.SubscribeSingleInvoiceRequest, ...grpc.CallOption) (wrapper.SubscribeSingleInvoiceWrapper, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *invoicesrpc.SubscribeSingleInvoiceRequest, ...grpc.CallOption) wrapper.SubscribeSingleInvoiceWrapper); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wrapper.SubscribeSingleInvoiceWrapper)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *invoicesrpc.SubscribeSingleInvoiceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeTransactions provides a mock function with given fields: ctx, req, options
func (_m *LightningClientWrapper) SubscribeTransactions(ctx context.Context, req *lnrpc.GetTransactionsRequest, options ...grpc.CallOption) (wrapper.SubscribeTransactionsWrapper, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeTransactions")
	}

	var r0 wrapper.SubscribeTransactionsWrapper
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.GetTransactionsRequest, ...grpc.CallOption) (wrapper.SubscribeTransactionsWrapper, error)); ok {
		return rf(ctx, req, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *lnrpc.GetTransactionsRequest, ...grpc.CallOption) wrapper.SubscribeTransactionsWrapper); ok {
		r0 = rf(ctx, req, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wrapper.SubscribeTransactionsWrapper)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *lnrpc.GetTransactionsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLightningClientWrapper creates a new instance of LightningClientWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLightningClientWrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *LightningClientWrapper {
	mock := &LightningClientWrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
