// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/flokiorg/lokihub/loki"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLokiService creates a new instance of MockLokiService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLokiService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLokiService {
	mock := &MockLokiService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLokiService is an autogenerated mock type for the LokiService type
type MockLokiService struct {
	mock.Mock
}

type MockLokiService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLokiService) EXPECT() *MockLokiService_Expecter {
	return &MockLokiService_Expecter{mock: &_m.Mock}
}

// GetFlokicoinRate provides a mock function for the type MockLokiService
func (_mock *MockLokiService) GetFlokicoinRate(ctx context.Context) (*loki.FlokicoinRate, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFlokicoinRate")
	}

	var r0 *loki.FlokicoinRate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*loki.FlokicoinRate, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *loki.FlokicoinRate); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*loki.FlokicoinRate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLokiService_GetFlokicoinRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlokicoinRate'
type MockLokiService_GetFlokicoinRate_Call struct {
	*mock.Call
}

// GetFlokicoinRate is a helper method to define mock.On call
//   - ctx
func (_e *MockLokiService_Expecter) GetFlokicoinRate(ctx interface{}) *MockLokiService_GetFlokicoinRate_Call {
	return &MockLokiService_GetFlokicoinRate_Call{Call: _e.mock.On("GetFlokicoinRate", ctx)}
}

func (_c *MockLokiService_GetFlokicoinRate_Call) Run(run func(ctx context.Context)) *MockLokiService_GetFlokicoinRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLokiService_GetFlokicoinRate_Call) Return(bitcoinRate *loki.FlokicoinRate, err error) *MockLokiService_GetFlokicoinRate_Call {
	_c.Call.Return(bitcoinRate, err)
	return _c
}

func (_c *MockLokiService_GetFlokicoinRate_Call) RunAndReturn(run func(ctx context.Context) (*loki.FlokicoinRate, error)) *MockLokiService_GetFlokicoinRate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrencies provides a mock function for the type MockLokiService
func (_mock *MockLokiService) GetCurrencies(ctx context.Context) (map[string]loki.LokiCurrency, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencies")
	}

	var r0 map[string]loki.LokiCurrency
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]loki.LokiCurrency, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]loki.LokiCurrency); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]loki.LokiCurrency)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLokiService_GetCurrencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrencies'
type MockLokiService_GetCurrencies_Call struct {
	*mock.Call
}

// GetCurrencies is a helper method to define mock.On call
//   - ctx
func (_e *MockLokiService_Expecter) GetCurrencies(ctx interface{}) *MockLokiService_GetCurrencies_Call {
	return &MockLokiService_GetCurrencies_Call{Call: _e.mock.On("GetCurrencies", ctx)}
}

func (_c *MockLokiService_GetCurrencies_Call) Run(run func(ctx context.Context)) *MockLokiService_GetCurrencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLokiService_GetCurrencies_Call) Return(currencies map[string]loki.LokiCurrency, err error) *MockLokiService_GetCurrencies_Call {
	_c.Call.Return(currencies, err)
	return _c
}

func (_c *MockLokiService_GetCurrencies_Call) RunAndReturn(run func(ctx context.Context) (map[string]loki.LokiCurrency, error)) *MockLokiService_GetCurrencies_Call {
	_c.Call.Return(run)
	return _c
}

// GetInfo provides a mock function for the type MockLokiService
func (_mock *MockLokiService) GetInfo(ctx context.Context) (*loki.LokiInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 *loki.LokiInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*loki.LokiInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *loki.LokiInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*loki.LokiInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLokiService_GetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfo'
type MockLokiService_GetInfo_Call struct {
	*mock.Call
}

// GetInfo is a helper method to define mock.On call
//   - ctx
func (_e *MockLokiService_Expecter) GetInfo(ctx interface{}) *MockLokiService_GetInfo_Call {
	return &MockLokiService_GetInfo_Call{Call: _e.mock.On("GetInfo", ctx)}
}

func (_c *MockLokiService_GetInfo_Call) Run(run func(ctx context.Context)) *MockLokiService_GetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLokiService_GetInfo_Call) Return(lokiInfo *loki.LokiInfo, err error) *MockLokiService_GetInfo_Call {
	_c.Call.Return(lokiInfo, err)
	return _c
}

func (_c *MockLokiService_GetInfo_Call) RunAndReturn(run func(ctx context.Context) (*loki.LokiInfo, error)) *MockLokiService_GetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetFAQ provides a mock function for the type MockLokiService
func (_mock *MockLokiService) GetFAQ(ctx context.Context) ([]loki.FAQ, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFAQ")
	}

	var r0 []loki.FAQ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]loki.FAQ, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []loki.FAQ); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]loki.FAQ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLokiService_GetFAQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFAQ'
type MockLokiService_GetFAQ_Call struct {
	*mock.Call
}

// GetFAQ is a helper method to define mock.On call
//   - ctx
func (_e *MockLokiService_Expecter) GetFAQ(ctx interface{}) *MockLokiService_GetFAQ_Call {
	return &MockLokiService_GetFAQ_Call{Call: _e.mock.On("GetFAQ", ctx)}
}

func (_c *MockLokiService_GetFAQ_Call) Run(run func(ctx context.Context)) *MockLokiService_GetFAQ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLokiService_GetFAQ_Call) Return(faq []loki.FAQ, err error) *MockLokiService_GetFAQ_Call {
	_c.Call.Return(faq, err)
	return _c
}

func (_c *MockLokiService_GetFAQ_Call) RunAndReturn(run func(ctx context.Context) ([]loki.FAQ, error)) *MockLokiService_GetFAQ_Call {
	_c.Call.Return(run)
	return _c
}
