// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/flokiorg/lokihub/appstore"
	"github.com/flokiorg/lokihub/config"
	"github.com/flokiorg/lokihub/events"
	"github.com/flokiorg/lokihub/keys"
	"github.com/flokiorg/lokihub/lnclient"
	"github.com/flokiorg/lokihub/loki"
	"github.com/flokiorg/lokihub/service"
	"github.com/flokiorg/lokihub/swaps"
	"github.com/flokiorg/lokihub/transactions"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetLokiSvc provides a mock function for the type MockService
func (_mock *MockService) GetLokiSvc() loki.LokiService {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLokiSvc")
	}

	var r0 loki.LokiService
	if returnFunc, ok := ret.Get(0).(func() loki.LokiService); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(loki.LokiService)
		}
	}
	return r0
}

// GetAppStoreSvc provides a mock function for the type MockService
func (_mock *MockService) GetAppStoreSvc() appstore.Service {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAppStoreSvc")
	}

	var r0 appstore.Service
	if returnFunc, ok := ret.Get(0).(func() appstore.Service); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(appstore.Service)
		}
	}
	return r0
}

// MockService_GetLokiSvc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLokiSvc'
type MockService_GetLokiSvc_Call struct {
	*mock.Call
}

// GetLokiSvc is a helper method to define mock.On call
func (_e *MockService_Expecter) GetLokiSvc() *MockService_GetLokiSvc_Call {
	return &MockService_GetLokiSvc_Call{Call: _e.mock.On("GetLokiSvc")}
}

func (_c *MockService_GetLokiSvc_Call) Run(run func()) *MockService_GetLokiSvc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetLokiSvc_Call) Return(lokiService loki.LokiService) *MockService_GetLokiSvc_Call {
	_c.Call.Return(lokiService)
	return _c
}

func (_c *MockService_GetLokiSvc_Call) RunAndReturn(run func() loki.LokiService) *MockService_GetLokiSvc_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type MockService
func (_mock *MockService) GetConfig() config.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 config.Config
	if returnFunc, ok := ret.Get(0).(func() config.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Config)
		}
	}
	return r0
}

// MockService_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockService_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockService_Expecter) GetConfig() *MockService_GetConfig_Call {
	return &MockService_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockService_GetConfig_Call) Run(run func()) *MockService_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetConfig_Call) Return(config1 config.Config) *MockService_GetConfig_Call {
	_c.Call.Return(config1)
	return _c
}

func (_c *MockService_GetConfig_Call) RunAndReturn(run func() config.Config) *MockService_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetDB provides a mock function for the type MockService
func (_mock *MockService) GetDB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockService_GetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDB'
type MockService_GetDB_Call struct {
	*mock.Call
}

// GetDB is a helper method to define mock.On call
func (_e *MockService_Expecter) GetDB() *MockService_GetDB_Call {
	return &MockService_GetDB_Call{Call: _e.mock.On("GetDB")}
}

func (_c *MockService_GetDB_Call) Run(run func()) *MockService_GetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetDB_Call) Return(dB *gorm.DB) *MockService_GetDB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockService_GetDB_Call) RunAndReturn(run func() *gorm.DB) *MockService_GetDB_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventPublisher provides a mock function for the type MockService
func (_mock *MockService) GetEventPublisher() events.EventPublisher {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEventPublisher")
	}

	var r0 events.EventPublisher
	if returnFunc, ok := ret.Get(0).(func() events.EventPublisher); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(events.EventPublisher)
		}
	}
	return r0
}

// MockService_GetEventPublisher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventPublisher'
type MockService_GetEventPublisher_Call struct {
	*mock.Call
}

// GetEventPublisher is a helper method to define mock.On call
func (_e *MockService_Expecter) GetEventPublisher() *MockService_GetEventPublisher_Call {
	return &MockService_GetEventPublisher_Call{Call: _e.mock.On("GetEventPublisher")}
}

func (_c *MockService_GetEventPublisher_Call) Run(run func()) *MockService_GetEventPublisher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetEventPublisher_Call) Return(eventPublisher events.EventPublisher) *MockService_GetEventPublisher_Call {
	_c.Call.Return(eventPublisher)
	return _c
}

func (_c *MockService_GetEventPublisher_Call) RunAndReturn(run func() events.EventPublisher) *MockService_GetEventPublisher_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeys provides a mock function for the type MockService
func (_mock *MockService) GetKeys() keys.Keys {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKeys")
	}

	var r0 keys.Keys
	if returnFunc, ok := ret.Get(0).(func() keys.Keys); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(keys.Keys)
		}
	}
	return r0
}

// MockService_GetKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeys'
type MockService_GetKeys_Call struct {
	*mock.Call
}

// GetKeys is a helper method to define mock.On call
func (_e *MockService_Expecter) GetKeys() *MockService_GetKeys_Call {
	return &MockService_GetKeys_Call{Call: _e.mock.On("GetKeys")}
}

func (_c *MockService_GetKeys_Call) Run(run func()) *MockService_GetKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetKeys_Call) Return(keys1 keys.Keys) *MockService_GetKeys_Call {
	_c.Call.Return(keys1)
	return _c
}

func (_c *MockService_GetKeys_Call) RunAndReturn(run func() keys.Keys) *MockService_GetKeys_Call {
	_c.Call.Return(run)
	return _c
}

// GetLNClient provides a mock function for the type MockService
func (_mock *MockService) GetLNClient() lnclient.LNClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLNClient")
	}

	var r0 lnclient.LNClient
	if returnFunc, ok := ret.Get(0).(func() lnclient.LNClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(lnclient.LNClient)
		}
	}
	return r0
}

// MockService_GetLNClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLNClient'
type MockService_GetLNClient_Call struct {
	*mock.Call
}

// GetLNClient is a helper method to define mock.On call
func (_e *MockService_Expecter) GetLNClient() *MockService_GetLNClient_Call {
	return &MockService_GetLNClient_Call{Call: _e.mock.On("GetLNClient")}
}

func (_c *MockService_GetLNClient_Call) Run(run func()) *MockService_GetLNClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetLNClient_Call) Return(lNClient lnclient.LNClient) *MockService_GetLNClient_Call {
	_c.Call.Return(lNClient)
	return _c
}

func (_c *MockService_GetLNClient_Call) RunAndReturn(run func() lnclient.LNClient) *MockService_GetLNClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelayStatuses provides a mock function for the type MockService
func (_mock *MockService) GetRelayStatuses() []service.RelayStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRelayStatuses")
	}

	var r0 []service.RelayStatus
	if returnFunc, ok := ret.Get(0).(func() []service.RelayStatus); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.RelayStatus)
		}
	}
	return r0
}

// MockService_GetRelayStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelayStatuses'
type MockService_GetRelayStatuses_Call struct {
	*mock.Call
}

// GetRelayStatuses is a helper method to define mock.On call
func (_e *MockService_Expecter) GetRelayStatuses() *MockService_GetRelayStatuses_Call {
	return &MockService_GetRelayStatuses_Call{Call: _e.mock.On("GetRelayStatuses")}
}

func (_c *MockService_GetRelayStatuses_Call) Run(run func()) *MockService_GetRelayStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetRelayStatuses_Call) Return(relayStatuss []service.RelayStatus) *MockService_GetRelayStatuses_Call {
	_c.Call.Return(relayStatuss)
	return _c
}

func (_c *MockService_GetRelayStatuses_Call) RunAndReturn(run func() []service.RelayStatus) *MockService_GetRelayStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// GetStartupState provides a mock function for the type MockService
func (_mock *MockService) GetStartupState() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStartupState")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockService_GetStartupState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStartupState'
type MockService_GetStartupState_Call struct {
	*mock.Call
}

// GetStartupState is a helper method to define mock.On call
func (_e *MockService_Expecter) GetStartupState() *MockService_GetStartupState_Call {
	return &MockService_GetStartupState_Call{Call: _e.mock.On("GetStartupState")}
}

func (_c *MockService_GetStartupState_Call) Run(run func()) *MockService_GetStartupState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetStartupState_Call) Return(s string) *MockService_GetStartupState_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockService_GetStartupState_Call) RunAndReturn(run func() string) *MockService_GetStartupState_Call {
	_c.Call.Return(run)
	return _c
}

// GetSwapsService provides a mock function for the type MockService
func (_mock *MockService) GetSwapsService() swaps.SwapsService {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSwapsService")
	}

	var r0 swaps.SwapsService
	if returnFunc, ok := ret.Get(0).(func() swaps.SwapsService); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(swaps.SwapsService)
		}
	}
	return r0
}

// MockService_GetSwapsService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSwapsService'
type MockService_GetSwapsService_Call struct {
	*mock.Call
}

// GetSwapsService is a helper method to define mock.On call
func (_e *MockService_Expecter) GetSwapsService() *MockService_GetSwapsService_Call {
	return &MockService_GetSwapsService_Call{Call: _e.mock.On("GetSwapsService")}
}

func (_c *MockService_GetSwapsService_Call) Run(run func()) *MockService_GetSwapsService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetSwapsService_Call) Return(swapsService swaps.SwapsService) *MockService_GetSwapsService_Call {
	_c.Call.Return(swapsService)
	return _c
}

func (_c *MockService_GetSwapsService_Call) RunAndReturn(run func() swaps.SwapsService) *MockService_GetSwapsService_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionsService provides a mock function for the type MockService
func (_mock *MockService) GetTransactionsService() transactions.TransactionsService {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsService")
	}

	var r0 transactions.TransactionsService
	if returnFunc, ok := ret.Get(0).(func() transactions.TransactionsService); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transactions.TransactionsService)
		}
	}
	return r0
}

// MockService_GetTransactionsService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionsService'
type MockService_GetTransactionsService_Call struct {
	*mock.Call
}

// GetTransactionsService is a helper method to define mock.On call
func (_e *MockService_Expecter) GetTransactionsService() *MockService_GetTransactionsService_Call {
	return &MockService_GetTransactionsService_Call{Call: _e.mock.On("GetTransactionsService")}
}

func (_c *MockService_GetTransactionsService_Call) Run(run func()) *MockService_GetTransactionsService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetTransactionsService_Call) Return(transactionsService transactions.TransactionsService) *MockService_GetTransactionsService_Call {
	_c.Call.Return(transactionsService)
	return _c
}

func (_c *MockService_GetTransactionsService_Call) RunAndReturn(run func() transactions.TransactionsService) *MockService_GetTransactionsService_Call {
	_c.Call.Return(run)
	return _c
}

// InitSwapsService provides a mock function for the type MockService
func (_mock *MockService) InitSwapsService() {
	_mock.Called()
	return
}

// MockService_InitSwapsService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitSwapsService'
type MockService_InitSwapsService_Call struct {
	*mock.Call
}

// InitSwapsService is a helper method to define mock.On call
func (_e *MockService_Expecter) InitSwapsService() *MockService_InitSwapsService_Call {
	return &MockService_InitSwapsService_Call{Call: _e.mock.On("InitSwapsService")}
}

func (_c *MockService_InitSwapsService_Call) Run(run func()) *MockService_InitSwapsService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_InitSwapsService_Call) Return() *MockService_InitSwapsService_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_InitSwapsService_Call) RunAndReturn(run func()) *MockService_InitSwapsService_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type MockService
func (_mock *MockService) Shutdown(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx
func (_e *MockService_Expecter) Shutdown(ctx interface{}) *MockService_Shutdown_Call {
	return &MockService_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockService_Shutdown_Call) Run(run func(ctx context.Context)) *MockService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Shutdown_Call) Return() *MockService_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Shutdown_Call) RunAndReturn(run func(ctx context.Context)) *MockService_Shutdown_Call {
	_c.Run(run)
	return _c
}

// StartApp provides a mock function for the type MockService
func (_mock *MockService) StartApp(encryptionKey string) error {
	ret := _mock.Called(encryptionKey)

	if len(ret) == 0 {
		panic("no return value specified for StartApp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(encryptionKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_StartApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartApp'
type MockService_StartApp_Call struct {
	*mock.Call
}

// StartApp is a helper method to define mock.On call
//   - encryptionKey
func (_e *MockService_Expecter) StartApp(encryptionKey interface{}) *MockService_StartApp_Call {
	return &MockService_StartApp_Call{Call: _e.mock.On("StartApp", encryptionKey)}
}

func (_c *MockService_StartApp_Call) Run(run func(encryptionKey string)) *MockService_StartApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_StartApp_Call) Return(err error) *MockService_StartApp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_StartApp_Call) RunAndReturn(run func(encryptionKey string) error) *MockService_StartApp_Call {
	_c.Call.Return(run)
	return _c
}

// StopApp provides a mock function for the type MockService
func (_mock *MockService) StopApp(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockService_StopApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopApp'
type MockService_StopApp_Call struct {
	*mock.Call
}

// StopApp is a helper method to define mock.On call
//   - ctx
func (_e *MockService_Expecter) StopApp(ctx interface{}) *MockService_StopApp_Call {
	return &MockService_StopApp_Call{Call: _e.mock.On("StopApp", ctx)}
}

func (_c *MockService_StopApp_Call) Run(run func(ctx context.Context)) *MockService_StopApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_StopApp_Call) Return() *MockService_StopApp_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_StopApp_Call) RunAndReturn(run func(ctx context.Context)) *MockService_StopApp_Call {
	_c.Run(run)
	return _c
}

// ReloadNostr provides a mock function for the type MockService
func (_mock *MockService) ReloadNostr() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReloadNostr")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ReloadNostr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReloadNostr'
type MockService_ReloadNostr_Call struct {
	*mock.Call
}

// ReloadNostr is a helper method to define mock.On call
func (_e *MockService_Expecter) ReloadNostr() *MockService_ReloadNostr_Call {
	return &MockService_ReloadNostr_Call{Call: _e.mock.On("ReloadNostr")}
}

func (_c *MockService_ReloadNostr_Call) Run(run func()) *MockService_ReloadNostr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_ReloadNostr_Call) Return(err error) *MockService_ReloadNostr_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ReloadNostr_Call) RunAndReturn(run func() error) *MockService_ReloadNostr_Call {
	_c.Call.Return(run)
	return _c
}

// WarmCircleFollowingCache provides a mock function for the type MockService
func (_mock *MockService) WarmCircleFollowingCache(ctx context.Context, providerPubkey string) (map[string]struct{}, error) {
	ret := _mock.Called(ctx, providerPubkey)

	if len(ret) == 0 {
		panic("no return value specified for WarmCircleFollowingCache")
	}

	var r0 map[string]struct{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]struct{}, error)); ok {
		return returnFunc(ctx, providerPubkey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]struct{}); ok {
		r0 = returnFunc(ctx, providerPubkey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]struct{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, providerPubkey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_WarmCircleFollowingCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarmCircleFollowingCache'
type MockService_WarmCircleFollowingCache_Call struct {
	*mock.Call
}

// WarmCircleFollowingCache is a helper method to define mock.On call
//   - ctx
//   - providerPubkey
func (_e *MockService_Expecter) WarmCircleFollowingCache(ctx interface{}, providerPubkey interface{}) *MockService_WarmCircleFollowingCache_Call {
	return &MockService_WarmCircleFollowingCache_Call{Call: _e.mock.On("WarmCircleFollowingCache", ctx, providerPubkey)}
}

func (_c *MockService_WarmCircleFollowingCache_Call) Run(run func(ctx context.Context, providerPubkey string)) *MockService_WarmCircleFollowingCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_WarmCircleFollowingCache_Call) Return(contacts map[string]struct{}, err error) *MockService_WarmCircleFollowingCache_Call {
	_c.Call.Return(contacts, err)
	return _c
}

func (_c *MockService_WarmCircleFollowingCache_Call) RunAndReturn(run func(ctx context.Context, providerPubkey string) (map[string]struct{}, error)) *MockService_WarmCircleFollowingCache_Call {
	_c.Call.Return(run)
	return _c
}

// WarmGeneralRelays provides a mock function for the type MockService
func (_mock *MockService) WarmGeneralRelays() {
	_mock.Called()
	return
}

// MockService_WarmGeneralRelays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarmGeneralRelays'
type MockService_WarmGeneralRelays_Call struct {
	*mock.Call
}

// WarmGeneralRelays is a helper method to define mock.On call
func (_e *MockService_Expecter) WarmGeneralRelays() *MockService_WarmGeneralRelays_Call {
	return &MockService_WarmGeneralRelays_Call{Call: _e.mock.On("WarmGeneralRelays")}
}

func (_c *MockService_WarmGeneralRelays_Call) Run(run func()) *MockService_WarmGeneralRelays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_WarmGeneralRelays_Call) Return() *MockService_WarmGeneralRelays_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_WarmGeneralRelays_Call) RunAndReturn(run func()) *MockService_WarmGeneralRelays_Call {
	_c.Run(run)
	return _c
}

// ContactCount provides a mock function for the type MockService
func (_mock *MockService) ContactCount(ctx context.Context, ownerPubkey string) (int, error) {
	ret := _mock.Called(ctx, ownerPubkey)

	if len(ret) == 0 {
		panic("no return value specified for ContactCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, ownerPubkey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, ownerPubkey)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ownerPubkey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ContactCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContactCount'
type MockService_ContactCount_Call struct {
	*mock.Call
}

// ContactCount is a helper method to define mock.On call
//   - ctx
//   - ownerPubkey
func (_e *MockService_Expecter) ContactCount(ctx interface{}, ownerPubkey interface{}) *MockService_ContactCount_Call {
	return &MockService_ContactCount_Call{Call: _e.mock.On("ContactCount", ctx, ownerPubkey)}
}

func (_c *MockService_ContactCount_Call) Run(run func(ctx context.Context, ownerPubkey string)) *MockService_ContactCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_ContactCount_Call) Return(count int, err error) *MockService_ContactCount_Call {
	_c.Call.Return(count, err)
	return _c
}

func (_c *MockService_ContactCount_Call) RunAndReturn(run func(ctx context.Context, ownerPubkey string) (int, error)) *MockService_ContactCount_Call {
	_c.Call.Return(run)
	return _c
}

// PeekContactCount provides a mock function for the type MockService
func (_mock *MockService) PeekContactCount(ownerPubkey string) (int, bool) {
	ret := _mock.Called(ownerPubkey)

	if len(ret) == 0 {
		panic("no return value specified for PeekContactCount")
	}

	var r0 int
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (int, bool)); ok {
		return returnFunc(ownerPubkey)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(ownerPubkey)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(ownerPubkey)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockService_PeekContactCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeekContactCount'
type MockService_PeekContactCount_Call struct {
	*mock.Call
}

// PeekContactCount is a helper method to define mock.On call
//   - ownerPubkey
func (_e *MockService_Expecter) PeekContactCount(ownerPubkey interface{}) *MockService_PeekContactCount_Call {
	return &MockService_PeekContactCount_Call{Call: _e.mock.On("PeekContactCount", ownerPubkey)}
}

func (_c *MockService_PeekContactCount_Call) Run(run func(ownerPubkey string)) *MockService_PeekContactCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_PeekContactCount_Call) Return(count int, ok bool) *MockService_PeekContactCount_Call {
	_c.Call.Return(count, ok)
	return _c
}

func (_c *MockService_PeekContactCount_Call) RunAndReturn(run func(ownerPubkey string) (int, bool)) *MockService_PeekContactCount_Call {
	_c.Call.Return(run)
	return _c
}

// PeekContactSyncedAt provides a mock function for the type MockService
func (_mock *MockService) PeekContactSyncedAt(ownerPubkey string) (time.Time, bool) {
	ret := _mock.Called(ownerPubkey)

	if len(ret) == 0 {
		panic("no return value specified for PeekContactSyncedAt")
	}

	var r0 time.Time
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (time.Time, bool)); ok {
		return returnFunc(ownerPubkey)
	}
	if returnFunc, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = returnFunc(ownerPubkey)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(ownerPubkey)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockService_PeekContactSyncedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeekContactSyncedAt'
type MockService_PeekContactSyncedAt_Call struct {
	*mock.Call
}

// PeekContactSyncedAt is a helper method to define mock.On call
//   - ownerPubkey
func (_e *MockService_Expecter) PeekContactSyncedAt(ownerPubkey interface{}) *MockService_PeekContactSyncedAt_Call {
	return &MockService_PeekContactSyncedAt_Call{Call: _e.mock.On("PeekContactSyncedAt", ownerPubkey)}
}

func (_c *MockService_PeekContactSyncedAt_Call) Run(run func(ownerPubkey string)) *MockService_PeekContactSyncedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_PeekContactSyncedAt_Call) Return(syncedAt time.Time, ok bool) *MockService_PeekContactSyncedAt_Call {
	_c.Call.Return(syncedAt, ok)
	return _c
}

func (_c *MockService_PeekContactSyncedAt_Call) RunAndReturn(run func(ownerPubkey string) (time.Time, bool)) *MockService_PeekContactSyncedAt_Call {
	_c.Call.Return(run)
	return _c
}
