// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	lnrpc "github.com/flokiorg/flnd/lnrpc"
	mock "github.com/stretchr/testify/mock"
)

// SubscribePaymentWrapper is an autogenerated mock type for the SubscribePaymentWrapper type
type SubscribePaymentWrapper struct {
	mock.Mock
}

// Recv provides a mock function with no fields
func (_m *SubscribePaymentWrapper) Recv() (*lnrpc.Payment, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *lnrpc.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func() (*lnrpc.Payment, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *lnrpc.Payment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lnrpc.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSubscribePaymentWrapper creates a new instance of SubscribePaymentWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscribePaymentWrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscribePaymentWrapper {
	mock := &SubscribePaymentWrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
