package service

import (
	"context"

	"github.com/flokiorg/lokihub/events"
	"github.com/flokiorg/lokihub/logger"
	"github.com/nbd-wtf/go-nostr"
)

type deleteAppConsumer struct {
	events.EventSubscriber
	// walletPubkey is the wallet this consumer belongs to, or "" for the one
	// registered alongside the shared NIP-47 subscription, which serves every
	// app wallet (see startTrustedRelaySubscription).
	walletPubkey string
	pool         *nostr.SimplePool
	// cancelSubscription is nil in the shared case: there is no per-wallet
	// subscription to cancel, the wallet is dropped from the registry instead.
	cancelSubscription func()
	svc                *service
}

// When an app is deleted, unsubscribe from events for that app on the relay
// and publish a deletion event for that app's info event
func (s *deleteAppConsumer) ConsumeEvent(ctx context.Context, event *events.Event, globalProperties map[string]interface{}) {
	if event.Event != "nwc_app_deleted" {
		return
	}
	properties, ok := event.Properties.(map[string]interface{})
	if !ok {
		logger.Logger.Error().Interface("event", event).Msg("Failed to cast event.Properties to map")
		return
	}
	id, ok := properties["id"].(uint)
	if !ok {
		logger.Logger.Error().Interface("event", event).Msg("missing id in properties event")
		return
	}

	walletPrivKey, err := s.svc.keys.GetAppWalletKey(id)
	if err != nil {
		logger.Logger.Error().Err(err).Uint("id", id).Msg("Failed to calculate app wallet priv key")
		return
	}
	walletPubKey, err := nostr.GetPublicKey(walletPrivKey)
	if err != nil {
		logger.Logger.Error().Err(err).Uint("id", id).Msg("Failed to calculate app wallet pub key")
		return
	}
	// Note: for legacy apps this check will always return false as the wallet pubkey
	// generated by the id will not match the master key which is used for all legacy apps
	// A per-wallet consumer acts only on its own wallet; the shared one
	// (walletPubkey == "") acts on every app wallet.
	shared := s.walletPubkey == ""
	if shared || s.walletPubkey == walletPubKey {
		// no longer need to listen to events for this wallet
		if s.cancelSubscription != nil {
			s.cancelSubscription()
		}
		if registry := s.svc.walletRegistry; registry != nil {
			logger.Logger.Debug().
				Uint("app_id", id).
				Str("wallet", walletPubKey).
				Msg("Scheduling a deleted app's wallet to stop being served")
			registry.RemoveAfterGrace(walletPubKey)
		}

		// remove this consumer as subscriber in eventPublisher — except the
		// shared one, which must stay registered for the next deletion
		if !shared {
			s.svc.eventPublisher.RemoveSubscriber(s)
		}

		// try to delete info event from relays (non-critical if it fails)
		// get nip47 event info for this app wallet key
		//
		// Looked up by walletPubKey — the pubkey of the app being deleted — not
		// s.walletPubkey. The shared consumer's own s.walletPubkey is "", and
		// GetNip47Info filters on Authors, so passing it matched nothing and
		// silently skipped every deletion. Since the shared consumer is what
		// runs whenever TrustedNwcRelay is on (the default), that meant info
		// events were effectively never deleted for any kind.
		nip47InfoEvent, err := s.svc.GetNip47Service().GetNip47Info(ctx, s.pool, walletPubKey)
		if err != nil {
			logger.Logger.Error().Err(err).Msg("Could not get nip47 info event")
			return
		}
		if nip47InfoEvent != nil {
			err = s.svc.nip47Service.PublishNip47InfoDeletion(ctx, s.pool, walletPubKey, walletPrivKey, nip47InfoEvent.ID)
			if err != nil {
				logger.Logger.Error().Err(err).Interface("event", event).Msg("Failed to publish nip47 info deletion")
			}
		}
	}
}
